# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eG9rbDPRkQwILE-yIitOwwBbEESchAfh
"""

import streamlit as st

st.set_page_config(
    page_title="SafeNest AI",
    layout="wide"
)

st.markdown("""
<style>

/* -------- FULL PAGE BACKGROUND -------- */
.stApp {
    background: linear-gradient(
        180deg,
        #BDD8E9 0%,
        #7BBDE8 40%,
        #6EA2B3 100%
    );
}

/* Remove default Streamlit padding */
.main .block-container {
    padding-top: 2rem;
    padding-bottom: 2rem;
}

/* -------- HERO SECTION -------- */
.hero {
    position: relative;
    padding: 4.5rem 2.5rem;
    border-radius: 28px;
    text-align: center;
    color: white;
    overflow: hidden;
    animation: zoomFade 1.4s ease-out;
    box-shadow: 0px 25px 50px rgba(0,0,0,0.25);

    background-image:
        linear-gradient(
            135deg,
            rgba(0, 29, 57, 0.85),
            rgba(10, 65, 116, 0.80),
            rgba(73, 118, 159, 0.75)
        ),
        url("https://images.unsplash.com/photo-1560448204-e02f11c3d0e2");

    background-size: cover;
    background-position: center;
}

/* Hero Title */
.hero h1 {
    font-size: 3.3rem;
    font-weight: 800;
    margin-bottom: 0.6rem;
    letter-spacing: 0.6px;
}

/* Hero Subtitle */
.hero p {
    font-size: 1.3rem;
    opacity: 0.95;
}

/* Animation */
@keyframes zoomFade {
    0% {
        transform: scale(0.85);
        opacity: 0;
    }
    100% {
        transform: scale(1);
        opacity: 1;
    }
}

</style>
""", unsafe_allow_html=True)







st.markdown("""
<style>

/* Hero with image + gradient overlay */
.hero {
    position: relative;
    padding: 4.5rem 2.5rem;
    border-radius: 26px;
    text-align: center;
    color: white;
    overflow: hidden;
    animation: zoomFade 1.4s ease-out;
    box-shadow: 0px 25px 50px rgba(0,0,0,0.25);

    /* Background image */
    background-image:
        linear-gradient(
            135deg,
            rgba(0, 29, 57, 0.85),
            rgba(10, 65, 116, 0.75),
            rgba(73, 118, 159, 0.65)
        ),
        url("https://images.unsplash.com/photo-1560448204-e02f11c3d0e2");

    background-size: cover;
    background-position: center;
}

/* Title */
.hero h1 {
    font-size: 3.3rem;
    font-weight: 800;
    margin-bottom: 0.6rem;
    letter-spacing: 0.5px;
}

/* Subtitle */
.hero p {
    font-size: 1.3rem;
    opacity: 0.95;
}

/* Animation */
@keyframes zoomFade {
    0% {
        transform: scale(0.85);
        opacity: 0;
    }
    100% {
        transform: scale(1);
        opacity: 1;
    }
}

</style>

<div class="hero">
    <h1> SafeNest AI</h1>
    <p>
        AI-Powered Property Safety & Risk Intelligence<br>
        <b>Building Trust, Safety & Better Living</b>
    </p>
</div>
""", unsafe_allow_html=True)



st.markdown("""
<style>

/* KPI grid */
.kpi-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
    gap: 1.5rem;
    margin-top: 2rem;
}

/* KPI card base */
.kpi-card {
    background: rgba(255, 255, 255, 0.25);
    backdrop-filter: blur(12px);
    -webkit-backdrop-filter: blur(12px);
    border-radius: 22px;
    padding: 1.8rem 1.5rem;
    box-shadow: 0px 15px 35px rgba(0,0,0,0.15);
    transition: all 0.35s ease;
    cursor: default;
}

/* Hover animation */
.kpi-card:hover {
    transform: translateY(-8px) scale(1.02);
    box-shadow: 0px 25px 45px rgba(0,0,0,0.25);
}

/* KPI title */
.kpi-title {
    font-size: 1rem;
    opacity: 0.85;
    margin-bottom: 0.4rem;
}

/* KPI value */
.kpi-value {
    font-size: 2.6rem;
    font-weight: 800;
}

/* Color variants */
.kpi-total { border-left: 6px solid #001D39; }
.kpi-high { border-left: 6px solid #ff4d4f; }
.kpi-moderate { border-left: 6px solid #faad14; }
.kpi-low { border-left: 6px solid #52c41a; }

</style>
""", unsafe_allow_html=True)





#######################################################

st.markdown("""
<style>
.kpi-card {
    background: rgba(255, 255, 255, 0.25);
    backdrop-filter: blur(12px);
    border-radius: 22px;
    padding: 1.8rem;
    box-shadow: 0px 15px 35px rgba(0,0,0,0.15);
}

.kpi-title {
    font-size: 0.8rem;
    opacity: 0.85;
}

.kpi-value {
    font-size: 2rem;
    font-weight: 800;
}

.kpi-total { border-left: 6px solid #001D39; }
.kpi-high { border-left: 6px solid #ff4d4f; }
.kpi-moderate { border-left: 6px solid #faad14; }
.kpi-low { border-left: 6px solid #52c41a; }
</style>
""", unsafe_allow_html=True)
c1, c2, c3, c4 = st.columns(4)

with c1:
    st.markdown("""
    <div class="kpi-card kpi-total">
        <div class="kpi-title"> Total Properties</div>
        <div class="kpi-value">300</div>
    </div>
    """, unsafe_allow_html=True)

with c2:
    st.markdown("""
    <div class="kpi-card kpi-high">
        <div class="kpi-title">🔴 High Risk</div>
        <div class="kpi-value">32</div>
    </div>
    """, unsafe_allow_html=True)

with c3:
    st.markdown("""
    <div class="kpi-card kpi-moderate">
        <div class="kpi-title">🟠 Moderate Risk</div>
        <div class="kpi-value">148</div>
    </div>
    """, unsafe_allow_html=True)

with c4:
    st.markdown("""
    <div class="kpi-card kpi-low">
        <div class="kpi-title">🟢 Low Risk</div>
        <div class="kpi-value">120</div>
    </div>
    """, unsafe_allow_html=True)
#######################################################################
from snowflake.snowpark.context import get_active_session

session = get_active_session()
st.markdown("""
<style>
.section-box {
    background: rgba(255, 255, 255, 0.35);
    backdrop-filter: blur(1px);
    border-radius: 20px;
    padding: 0.05rem;
    margin-top: 2.2rem;
    box-shadow: 0px 18px 39px rgba(0,0,0,0.18);
}

.section-title {
    text-align: center;
    font-size: 1.4rem;
    font-weight: 800;
    color: #001D39;
    margin-bottom: 0.4rem;
}

.section-subtitle {
    text-align: center;
    font-size: 0.95rem;
    opacity: 0.8;
    margin-bottom: 1.4rem;
}

.risk-pill {
    display: inline-block;
    padding: 0.4rem 1rem;
    border-radius: 20px;
    font-weight: 700;
    color: white;
    font-size: 0.85rem;
}
.risk-high { background: #ff4d4f; }
.risk-moderate { background: #faad14; }
.risk-low { background: #52c41a; }
</style>
""", unsafe_allow_html=True)
# -------------------------------
# EXPLORE PROPERTIES (NO EXPANDER)
# -------------------------------
with st.container():
    st.markdown('<div class="section-box">', unsafe_allow_html=True)

    st.markdown(
        """
        <div class="section-title">Explore Properties</div>
        <div class="section-subtitle">
            Select a property to view its safety risk, inspections, and AI insights
        </div>
        """,
        unsafe_allow_html=True
    )

    properties_df = session.sql("""
        SELECT
            property_id,
            property_name || ' (' || city || ')' AS label
        FROM properties
        ORDER BY property_name
    """).to_pandas()

    selected_label = st.selectbox(
        "Property",
        properties_df["LABEL"].tolist(),
        label_visibility="collapsed"
    )

    selected_property_id = int(
        properties_df.loc[
            properties_df["LABEL"] == selected_label,
            "PROPERTY_ID"
        ].values[0]
    )

    st.markdown('</div>', unsafe_allow_html=True)
# -------------------------------
# PROPERTY OVERVIEW (NO EXPANDER)
# -------------------------------
details_df = session.sql(f"""
    SELECT
        property_name,
        city,
        state,
        total_inspections,
        avg_severity_score,
        high_severity_issues,
        derived_risk_level
    FROM property_details
    WHERE property_id = {selected_property_id}
""").to_pandas()

if not details_df.empty:
    d = details_df.iloc[0]

    risk_class = {
        "High": "risk-high",
        "Moderate": "risk-moderate",
        "Low": "risk-low"
    }.get(d["DERIVED_RISK_LEVEL"], "risk-low")

    with st.container():
        st.markdown('<div class="section-box">', unsafe_allow_html=True)

        st.markdown(
            """
            <div class="section-title">Property Overview</div>
            <div class="section-subtitle">
                Key safety and inspection indicators for the selected property
            </div>
            """,
            unsafe_allow_html=True
        )

        st.markdown(f"### {d['PROPERTY_NAME']}")
        st.caption(f"📍 {d['CITY']}, {d['STATE']}")

        st.markdown(
            f"<span class='risk-pill {risk_class}'>"
            f"{d['DERIVED_RISK_LEVEL'].upper()} RISK</span>",
            unsafe_allow_html=True
        )

        st.write("")

        c1, c2, c3 = st.columns(3)

with c1:
    st.markdown(
        f"""
        <div class="glass-metric">
            <div class="glass-metric-value">{int(d['TOTAL_INSPECTIONS'])}</div>
            <div class="glass-metric-label">Inspections</div>
        </div>
        """,
        unsafe_allow_html=True
    )

with c2:
    st.markdown(
        f"""
        <div class="glass-metric">
            <div class="glass-metric-value">{round(d['AVG_SEVERITY_SCORE'], 2)}</div>
            <div class="glass-metric-label">Avg Severity</div>
        </div>
        """,
        unsafe_allow_html=True
    )

with c3:
    st.markdown(
        f"""
        <div class="glass-metric">
            <div class="glass-metric-value">{int(d['HIGH_SEVERITY_ISSUES'])}</div>
            <div class="glass-metric-label">High-Risk Issues</div>
        </div>
        """,
        unsafe_allow_html=True
    )

    st.markdown('</div>', unsafe_allow_html=True)
st.markdown("""
<style>

/* Small glass metric cards */
.glass-metric {
    background: rgba(255, 255, 255, 0.35);
    backdrop-filter: blur(10px);
    border-radius: 16px;
    padding: 1.2rem 1rem;
    text-align: center;
    box-shadow: 0px 10px 26px rgba(0,0,0,0.15);
}

.glass-metric-value {
    font-size: 1.9rem;
    font-weight: 800;
    color: #001D39;
}

.glass-metric-label {
    font-size: 0.85rem;
    opacity: 0.75;
}

</style>
""", unsafe_allow_html=True)
# -------------------------------
# -------------------------------
# RISK COMPOSITION DATA (REAL)
# -------------------------------
risk_df = session.sql(f"""
    SELECT
        HIGH_SEVERITY_ISSUES AS high_issues,
        (TOTAL_INSPECTIONS - HIGH_SEVERITY_ISSUES) AS other_issues
    FROM property_details
    WHERE property_id = {selected_property_id}
""").to_pandas()
if not risk_df.empty:
    high_issues = int(risk_df.iloc[0]["HIGH_ISSUES"])
    other_issues = int(risk_df.iloc[0]["OTHER_ISSUES"])

    chart_df = {
        "Category": ["High Severity Issues", "Other Inspections"],
        "Count": [high_issues, other_issues]
    }
import pandas as pd
import altair as alt

chart_df = pd.DataFrame(chart_df)

risk_chart = (
    alt.Chart(chart_df)
    .mark_arc(innerRadius=70)
    .encode(
        theta=alt.Theta("Count:Q"),
        color=alt.Color(
            "Category:N",
            scale=alt.Scale(
                domain=["High Severity Issues", "Other Inspections"],
                range=["#ff4d4f", "#91caff"]
            ),
            legend=alt.Legend(title="Inspection Type")
        ),
        tooltip=["Category:N", "Count:Q"]
    )
    .properties(
        background="transparent"
    )
    .configure_view(
        strokeOpacity=0
    )
)


# -------------------------------
# RISK COMPOSITION (GLASS BOX)
# -------------------------------
with st.container():
    st.markdown('<div class="section-box">', unsafe_allow_html=True)

    st.markdown(
        """
        <div class="section-title">Risk Composition</div>
        <div class="section-subtitle">
            Proportion of high-severity issues compared to total inspections
        </div>
        """,
        unsafe_allow_html=True
    )

    if high_issues == 0:
        st.success("No high-severity issues recorded for this property.")
    else:
        st.altair_chart(risk_chart, use_container_width=True)

    st.markdown('</div>', unsafe_allow_html=True)
# -------------------------------
st.markdown("""
<style>
@keyframes fadeSlide {
  from { opacity: 0; transform: translateY(14px); }
  to { opacity: 1; transform: translateY(0); }
}

.context-wrapper {
    background: rgba(255,255,255,0.28);
    backdrop-filter: blur(14px);
    border-radius: 22px;
    padding: 0rem;
    margin-top: 2.4rem;
    box-shadow: 0 18px 40px rgba(0,0,0,0.2);
    animation: fadeSlide 0.6s ease;
}

.context-card {
    background: rgba(255,255,255,0.35);
    border-radius: 16px;
    padding: 1rem 0.8rem;
    margin-bottom: 0.8rem;
    box-shadow: 0 10px 24px rgba(0,0,0,0.15);
    animation: fadeSlide 0.6s ease;
}

.context-stat {
    background: rgba(255,255,255,0.42);
    border-radius: 16px;
    padding: 1.2rem;
    text-align: center;
    box-shadow: 0 10px 22px rgba(0,0,0,0.14);
}

.context-value {
    font-size: 1.7rem;
    font-weight: 800;
    color: #001D39;
}

.context-label {
    font-size: 0.8rem;
    opacity: 0.75;
}

.review-stars {
    color: #f4b400;
    font-weight: 700;
}
</style>
""", unsafe_allow_html=True)
# -------------------------------
# -------------------------------
# PROPERTY CONTEXT DATA (REAL)
# -------------------------------
landmarks_df = session.sql(f"""
    SELECT landmark_name, distance_km
    FROM property_landmarks
    WHERE property_id = {selected_property_id}
    ORDER BY distance_km
""").to_pandas()

context_df = session.sql(f"""
    SELECT
        PROPERTY_NAME,
        YEAR_BUILT,
        TOTAL_INSPECTIONS,
        AVG_SEVERITY_SCORE,
        HIGH_SEVERITY_ISSUES,
        DERIVED_RISK_LEVEL
    FROM property_details
    WHERE property_id = {selected_property_id}
""").to_pandas()
# -------------------------------
# PROPERTY CONTEXT (FINAL, REAL)
# -------------------------------
with st.container():
    st.markdown('<div class="context-wrapper">', unsafe_allow_html=True)

    st.markdown(
        """
        <div class="section-title">Property Context</div>
        <div class="section-subtitle">
            Surroundings, building condition, and resident safety outlook
        </div>
        """,
        unsafe_allow_html=True
    )

    tab1, tab2, tab3 = st.tabs(
        ["📍 Surroundings", "🏢 Building Insights", "🤖 Safety Outlook"]
    )

    # ---- SURROUNDINGS ----
    with tab1:
        if landmarks_df.empty:
            st.info("No nearby landmarks available.")
        else:
            for _, row in landmarks_df.iterrows():
                st.markdown(
                    f"""
                    <div class="context-card">
                        <b>📍 {row['LANDMARK_NAME']}</b><br>
                        <span>{row['DISTANCE_KM']} km away</span>
                    </div>
                    """,
                    unsafe_allow_html=True
                )

    # ---- BUILDING INSIGHTS ----
    with tab2:
        if context_df.empty:
            st.info("No building insights available.")
        else:
            c = context_df.iloc[0]
            property_age = 2026 - int(c["YEAR_BUILT"]) if c["YEAR_BUILT"] else "N/A"

            col1, col2, col3 = st.columns(3)

            with col1:
                st.markdown(
                    f"""
                    <div class="context-stat">
                        <div class="context-value">{property_age}</div>
                        <div class="context-label">Property Age (Years)</div>
                    </div>
                    """,
                    unsafe_allow_html=True
                )

            with col2:
                st.markdown(
                    f"""
                    <div class="context-stat">
                        <div class="context-value">{int(c['TOTAL_INSPECTIONS'])}</div>
                        <div class="context-label">Inspections Conducted</div>
                    </div>
                    """,
                    unsafe_allow_html=True
                )

            with col3:
                st.markdown(
                    f"""
                    <div class="context-stat">
                        <div class="context-value">{round(c['AVG_SEVERITY_SCORE'],1)}</div>
                        <div class="context-label">Avg Severity Score</div>
                    </div>
                    """,
                    unsafe_allow_html=True
                )

    # ---- SAFETY OUTLOOK (DERIVED, AI-STYLE) ----
    with tab3:
        if context_df.empty:
            st.info("No safety outlook available.")
        else:
            c = context_df.iloc[0]

            outlook = (
                f"This property is classified as {c['DERIVED_RISK_LEVEL']} risk. "
                f"It has undergone {int(c['TOTAL_INSPECTIONS'])} inspections, "
                f"with {int(c['HIGH_SEVERITY_ISSUES'])} high-severity issues identified. "
                f"The average severity score of {round(c['AVG_SEVERITY_SCORE'],1)} "
                f"suggests that safety conditions require "
                f"{'immediate attention' if c['DERIVED_RISK_LEVEL']=='High' else 'regular monitoring'}."
            )

            st.markdown(
                f"""
                <div class="context-card">
                    <b>🧠 AI-Derived Safety Insight</b><br><br>
                    {outlook}
                </div>
                """,
                unsafe_allow_html=True
            )

    st.markdown('</div>', unsafe_allow_html=True)
st.markdown("""
<style>
@keyframes aiFadeUp {
  0% {
    opacity: 0;
    transform: translateY(24px) scale(0.96);
  }
  100% {
    opacity: 1;
    transform: translateY(0) scale(1);
  }
}

.ai-glass-box {
    background: linear-gradient(
        135deg,
        rgba(255,255,255,0.35),
        rgba(225,240,255,0.45)
    );
    backdrop-filter: blur(18px);
    border-radius: 26px;
    padding: 2.5rem;
    margin-top: 3.5rem;
    box-shadow: 0 26px 54px rgba(0,0,0,0.28);
    animation: aiFadeUp 0.9s ease forwards;
}

.ai-title {
    font-size: 1.65rem;
    font-weight: 900;
    text-align: center;
    color: #001D39;
    margin-bottom: 0.4rem;
}

.ai-subtitle {
    text-align: center;
    font-size: 0.95rem;
    opacity: 0.8;
    margin-bottom: 2rem;
}

.ai-content {
    font-size: 1.04rem;
    line-height: 1.85;
    color: #001D39;
    text-align: justify;
}
</style>
""", unsafe_allow_html=True)
# -----------------------------------
# AI SAFETY SUMMARY (LOGIC)
# -----------------------------------

# Safe default (never crashes UI)
ai_text = "AI safety summary is not available for this property yet."

ai_df = session.sql(f"""
    SELECT
        PROPERTY_NAME,
        YEAR_BUILT,
        TOTAL_INSPECTIONS,
        HIGH_SEVERITY_ISSUES,
        AVG_SEVERITY_SCORE,
        DERIVED_RISK_LEVEL
    FROM property_details
    WHERE property_id = {selected_property_id}
""").to_pandas()

if not ai_df.empty:
    a = ai_df.iloc[0]
    property_age = 2026 - int(a["YEAR_BUILT"]) if a["YEAR_BUILT"] else "unknown"

    prompt = f"""
You are an AI safety analyst assisting families, buyers, and housing regulators.

Property name: {a['PROPERTY_NAME']}
Property age: {property_age} years
Risk level: {a['DERIVED_RISK_LEVEL']}
Total inspections: {a['TOTAL_INSPECTIONS']}
High severity issues: {a['HIGH_SEVERITY_ISSUES']}
Average severity score: {a['AVG_SEVERITY_SCORE']}

Write a clear, calm, non-technical safety summary in 3 short paragraphs:
1) Overall safety risk
2) Likely causes or concerns
3) Recommended actions for residents or authorities

Avoid jargon. Be responsible and helpful.
"""

    ai_result_df = session.sql(f"""
        SELECT
            snowflake.cortex.complete(
                'mistral-large',
                {prompt!r}
            ) AS summary
    """).to_pandas()

    ai_text = ai_result_df.iloc[0]["SUMMARY"]

# Format for HTML
#ai_text = ai_text.replace("\n", "\n\n")
# -----------------------------------
# AI SAFETY SUMMARY (LOGIC — CLEAN)
# -----------------------------------
ai_text = ""

ai_df = session.sql(f"""
    SELECT
        PROPERTY_NAME,
        YEAR_BUILT,
        TOTAL_INSPECTIONS,
        HIGH_SEVERITY_ISSUES,
        AVG_SEVERITY_SCORE,
        DERIVED_RISK_LEVEL
    FROM property_details
    WHERE property_id = {selected_property_id}
""").to_pandas()

if not ai_df.empty:
    a = ai_df.iloc[0]
    property_age = 2026 - int(a["YEAR_BUILT"]) if a["YEAR_BUILT"] else "unknown"

    prompt = f"""
Write a safety summary in plain text ONLY.
Do NOT use HTML.
Do NOT use bullet points.
Write 3 short paragraphs separated by blank lines.

Property: {a['PROPERTY_NAME']}
Age: {property_age} years
Risk: {a['DERIVED_RISK_LEVEL']}
Inspections: {a['TOTAL_INSPECTIONS']}
High severity issues: {a['HIGH_SEVERITY_ISSUES']}
Average severity: {a['AVG_SEVERITY_SCORE']}
"""

    ai_df_out = session.sql(f"""
        SELECT snowflake.cortex.complete(
            'mistral-large',
            {prompt!r}
        ) AS summary
    """).to_pandas()

    ai_text = ai_df_out.iloc[0]["SUMMARY"]

# Convert AI text into HTML paragraphs safely
# Clean and format AI text into proper paragraphs
import re

paragraphs = [
    p.strip()
    for p in re.split(r"\n\s*\n+", ai_text)
    if p.strip()
]

ai_html = "".join(f"<p>{p}</p>" for p in paragraphs)

st.markdown(
    f"""
    <div class="ai-glass-box">
        <div class="ai-title">AI Safety Summary</div>
        <div class="ai-subtitle">
            Plain-language insights generated using Snowflake Intelligence
        </div>
        <div class="ai-content">
            {ai_html}
        </div>
    </div>
    """,
    unsafe_allow_html=True
)

# -----------------------------------
st.markdown("""
<style>
.floating-links {
    position: fixed;
    bottom: 24px;
    right: 24px;
    display: flex;
    align-items: center;
    gap: 16px;
    z-index: 9999;
}
.floating-tile {
    margin: 0 4px;     /* extra breathing room */
}

.floating-tile {
    width: 54px;
    height: 54px;
    border-radius: 16px;
    background: linear-gradient(
        135deg,
        rgba(255,255,255,0.35),
        rgba(220,240,255,0.45)
    );
    backdrop-filter: blur(14px);
    box-shadow: 0 14px 32px rgba(0,0,0,0.25);
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 1.4rem;
    cursor: pointer;
    transition: all 0.3s ease;
}

.floating-tile:hover {
    transform: scale(1.18);
    box-shadow: 0 20px 44px rgba(0,0,0,0.35);
}

.floating-tile a {
    text-decoration: none;
    color: #001D39;
}
</style>
""", unsafe_allow_html=True)
st.markdown(
    """
    <div class="floating-tile">
    <a href="https://www.linkedin.com/in/nikhil-rana-295532269/"
       target="_blank"
       title="LinkedIn">
        <svg width="26" height="26" viewBox="0 0 24 24" fill="#0A66C2" xmlns="http://www.w3.org/2000/svg">
            <path d="M4.98 3.5C4.98 4.88 3.88 6 2.5 6C1.12 6 0 4.88 0 3.5C0 2.12 1.12 1 2.5 1C3.88 1 4.98 2.12 4.98 3.5ZM0.5 8H4.5V24H0.5V8ZM8.5 8H12.3V10.1H12.35C12.88 9.1 14.18 8.05 16.1 8.05C20.2 8.05 21 10.65 21 14.1V24H17V15.3C17 13.2 16.95 10.9 14.5 10.9C12 10.9 11.6 12.9 11.6 15.2V24H7.6V8H8.5Z"/>
        </svg>
    </a>
</div>
<div class="floating-tile">
    <a href="https://github.com/phoenixgit321"
       target="_blank"
       title="GitHub">
        <svg width="26" height="26" viewBox="0 0 24 24" fill="#000000" xmlns="http://www.w3.org/2000/svg">
            <path d="M12 .5C5.73.5.5 5.74.5 12.03c0 5.11 3.29 9.44 7.86 10.97.58.1.79-.26.79-.57v-2.04c-3.2.7-3.87-1.39-3.87-1.39-.53-1.36-1.29-1.72-1.29-1.72-1.05-.73.08-.72.08-.72 1.16.08 1.77 1.2 1.77 1.2 1.03 1.77 2.7 1.26 3.36.96.1-.75.4-1.26.73-1.55-2.56-.3-5.26-1.28-5.26-5.7 0-1.26.45-2.29 1.19-3.1-.12-.29-.52-1.46.11-3.05 0 0 .97-.31 3.18 1.18a11.1 11.1 0 0 1 2.9-.39c.98 0 1.97.13 2.9.39 2.2-1.49 3.17-1.18 3.17-1.18.63 1.59.23 2.76.11 3.05.74.81 1.19 1.84 1.19 3.1 0 4.43-2.7 5.4-5.27 5.69.41.36.78 1.08.78 2.18v3.23c0 .31.21.67.8.56 4.56-1.53 7.85-5.86 7.85-10.97C23.5 5.74 18.27.5 12 .5z"/>
        </svg>
    </a>
</div>

    """,
    unsafe_allow_html=True
)